spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/test
  #    username: root
  #    password: root
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
